name: Deploy PXT site to GitHub Pages in kvantorium

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install PXT
        run: npm install -g pxt

      - name: Install deps (fixed for old PXT)
        run: |
          rm -rf node_modules package-lock.json
          npm pkg set devDependencies.typescript="3.9.10"
          npm pkg set devDependencies.@types/ws="7.4.0"
          npm install
      
      - name: Build static site
        run: pxt staticpkg --githubpages

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: built/packaged

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
